export const SET_SETTINGS = {
  HAS_FETCHED: 'SET_SETTINGS_HAS_FETCHED',
};
export const INCREMENT_SETTINGS = {
  HAS_FETCHED: 'INCREMENT_SETTINGS_HAS_FETCHED',
};
export const DECREMENT_SETTINGS = {
  HAS_FETCHED: 'DECREMENT_SETTINGS_HAS_FETCHED',
};
export const RESET_SETTINGS = {
  HAS_FETCHED: 'RESET_SETTINGS_HAS_FETCHED',
};
export const SKIP_GREETING = {
  HAS_FETCHED: 'SKIP_GREETING_HAS_FETCHED',
};
export const OPEN_TASK_LIST_MODAL = {
  HAS_FETCHED: 'OPEN_TASK_LIST_MODAL_HAS_FETCHED',
};
export const CLOSE_TASK_LIST_MODAL = {
  HAS_FETCHED: 'CLOSE_TASK_LIST_MODAL_HAS_FETCHED',
};
export const CHANGE_TASK_LIST_MODAL = {
  HAS_FETCHED: 'CHANGE_TASK_LIST_MODAL_HAS_FETCHED',
};
export const EDIT_TASK = {
  HAS_FETCHED: 'EDIT_TASK_HAS_FETCHED',
};
export const ENABLE_DELETE_MODE = {
  HAS_FETCHED: 'ENABLE_DELETE_MODE_HAS_FETCHED',
};
export const DISABLE_DELETE_MODE = {
  HAS_FETCHED: 'DISABLE_DELETE_MODE_HAS_FETCHED',
};
export const MOVE_TO_TRASH = {
  HAS_FETCHED: 'MOVE_TO_TRASH_HAS_FETCHED',
};
export const UPDATE_TRASH = {
  HAS_FETCHED: 'UPDATE_TRASH_HAS_FETCHED',
};
export const SHOW_DELETE_CONFIRMATION = {
  HAS_FETCHED: 'SHOW_DELETE_CONFIRMATION_HAS_FETCHED',
};

export const SAVE_TASK = {
  IS_FETCHING: 'SAVE_TASK_IS_FETCHING',
  HAS_FETCHED: 'SAVE_TASK_HAS_FETCHED',
};
export const GET_TASKS = {
  IS_FETCHING: 'GET_TASKS_IS_FETCHING',
  HAS_FETCHED: 'GET_TASKS_HAS_FETCHED',
};
export const UPDATE_TASK = {
  IS_FETCHING: 'UPDATE_TASK_IS_FETCHING',
  HAS_FETCHED: 'UPDATE_TASK_HAS_FETCHED',
};
export const DELETE_TASK = {
  IS_FETCHING: 'DELETE_TASK_IS_FETCHING',
  HAS_FETCHED: 'DELETE_TASK_HAS_FETCHED',
};
export const MOVE_TO_DAILY = {
  IS_FETCHING: 'MOVE_TO_DAILY_IS_FETCHING',
  HAS_FETCHED: 'MOVE_TO_DAILY_HAS_FETCHED',
};
export const SAVE_SETTINGS = {
  IS_FETCHING: 'SAVE_SETTINGS_IS_FETCHING',
  HAS_FETCHED: 'SAVE_SETTINGS_HAS_FETCHED',
};
export const UPDATE_TRASH_ITEM = {
  HAS_FETCHED: 'UPDATE_TRASH_ITEM_HAS_FETCHED',
};
export const DECLINE_DELETING = {
  HAS_FETCHED: 'DECLINE_DELETING_HAS_FETCHED',
};

export const INIT_TIMER = {
  IS_FETCHING: 'INIT_TIMER_IS_FETCHING',
  HAS_FETCHED: 'INIT_TIMER_HAS_FETCHED',
};

export const START_ITERATION = {
  HAS_FETCHED: 'START_ITERATION_HAS_FETCHED',
};

export const FINISH_ITERATION = {
  HAS_FETCHED: 'FINISH_ITERATION_HAS_FETCHED',
};

export const COUNT_DOWN = {
  HAS_FETCHED: 'COUNT_DOWN_HAS_FETCHED',
};
