export const SET_SETTINGS = 'SET_SETTINGS';
export const INCREMENT_SETTINGS = 'INCREMENT_SETTINGS';
export const DECREMENT_SETTINGS = 'DECREMENT_SETTINGS';
export const SAVE_SETTINGS_START = 'SAVE_SETTINGS_START';
export const SAVE_SETTINGS = 'SAVE_SETTINGS';
export const RESET_SETTINGS = 'RESET_SETTINGS';
